branch-defaults:
  master:
    environment: Nyclean-env
environment-defaults:
  Nyclean-env:
    branch: master
    repository: origin
global:
  application_name: NYClean
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Passenger with Ruby
    2.3 running on 64bit Amazon Linux/2.4.4
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
